import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
const script = new URL('./validate-native-model.mjs', import.meta.url).pathname;
const manifest = JSON.parse(await readFile(new URL('../runtime/native-codex/build-manifest.json', import.meta.url), 'utf8'));
function run(args, ms = 60000) { return new Promise((resolve, reject) => { const child = spawn(process.execPath, [script, ...args], { stdio: ['ignore', 'pipe', 'pipe'], env: { PATH: process.env.PATH || '/usr/bin:/bin' } }); let stdout = ''; let stderr = ''; const timer = setTimeout(() => { child.kill('SIGKILL'); reject(new Error('validator_test_timeout')); }, ms); child.stdout.on('data', (chunk) => { stdout += chunk; }); child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('error', (error) => { clearTimeout(timer); reject(error); }); child.on('close', (code) => { clearTimeout(timer); resolve({ code, stdout, stderr }); }); }); }
test('proves all five behaviors through a loopback provider and writes no admission', async () => { const result = await run([manifest.binaryPath]); assert.equal(result.code, 0, result.stderr); const report = JSON.parse(result.stdout); assert.deepEqual(report.checks, { streaming: true, toolContinuation: true, vision: true, cancellation: true, errors: true }); assert.equal(report.provider, 'loopback'); assert.equal(report.admissionWritten, false); assert.equal(report.sourceCommit, manifest.sourceCommit); assert.equal(report.binarySha256, manifest.binarySha256); assert.deepEqual(report.evidence, { modelRequests: 2, toolCalls: 1, unauthorizedRequests: 1, interruptedRequests: 1 }); assert.doesNotMatch(result.stdout + result.stderr, /local-only|NATIVE_ADMISSION_SKILL|data:image\//); });
test('rejects external-provider options before starting a binary', async () => { for (const args of [['/tmp/does-not-start', '--provider-url', 'https://provider.example/v1'], ['/tmp/does-not-start', '--allow-network']]) { const result = await run(args); assert.notEqual(result.code, 0); assert.match(result.stderr, /loopback-only/); } });
test('requires a binary argument', async () => { const result = await run([]); assert.equal(result.code, 2); assert.match(result.stderr, /Usage:/); });
